# Site settings
title: "The Correspondence"
description: "letters to humans"
baseurl: ""
url: "https://thecorrespondence.net"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  # - title: "twt"
  #   url: http://twitter.com/alixedi
  # - title: "git"
  #   url: http://github.com/alixedi
  # - title: "rss"
  #   url: /feed.xml
